services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: laravel-backend
    volumes:
      - ./backend:/var/www
      - ./backend/database:/var/www/database
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: angular-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"

